// GENERATED by @vike-data/universal-schema — do not edit by hand.
// Your schema is declared with defineSchema()/extendSchema() across your
// extensions; this file is derived from it. Re-run generation to update it.

import { Migration, Schema } from '@rudderjs/database'

export default class extends Migration {
  async up() {
    await Schema.create('invitations', (t) => {
      t.uuid('id').primary()
      t.uuid('organization_id').references('id').on('organizations').onDelete('cascade')
      t.string('email')
      t.string('role').default("member")
      t.string('token').unique()
      t.string('status').default("pending")
      t.timestamp('expires_at')
      t.timestamp('accepted_at').nullable()
      t.uuid('invited_by').nullable().references('id').on('users').onDelete('set null')
      t.timestamp('created_at').useCurrent()
      t.timestamp('updated_at').useCurrent()
    })
  }
}
