// The pure codegen core (generate.js): ORM/mode selection + the resolve -> order -> merge ->
// generate pipeline and its conflict gate. No fs, no Vike (the plugin wraps this).
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { defineSchema, extendSchema } from '@vike-data/vike-schema/schema'
import { resolveOrm, resolveMode, generateFromConfig } from '../generate.js'

const GENERATED = /GENERATED by @vike-data\/universal-schema/

const sampleConfig = () => ({
  schemas: [
    defineSchema('users', (t) => t.uuid('id').primary()),
    defineSchema('posts', (t) => t.uuid('author_id').references('users.id', { onDelete: 'cascade' })),
    extendSchema('users', (t) => t.string('nickname')),
  ],
})

test('resolveOrm: option wins, then env, then default drizzle (lowercased)', () => {
  const saved = process.env.VIKE_DATA_ORM
  try {
    delete process.env.VIKE_DATA_ORM
    assert.equal(resolveOrm(), 'drizzle')
    assert.equal(resolveOrm('Prisma'), 'prisma')
    process.env.VIKE_DATA_ORM = 'RUDDER'
    assert.equal(resolveOrm(), 'rudder') // env when no option
    assert.equal(resolveOrm('drizzle'), 'drizzle') // option beats env
  } finally {
    if (saved === undefined) delete process.env.VIKE_DATA_ORM
    else process.env.VIKE_DATA_ORM = saved
  }
})

test('resolveMode: option wins, else check only when VIKE_DATA_GEN=check', () => {
  const saved = process.env.VIKE_DATA_GEN
  try {
    delete process.env.VIKE_DATA_GEN
    assert.equal(resolveMode(), 'write')
    process.env.VIKE_DATA_GEN = 'check'
    assert.equal(resolveMode(), 'check')
    assert.equal(resolveMode('write'), 'write') // option beats env
    process.env.VIKE_DATA_GEN = 'something-else'
    assert.equal(resolveMode(), 'write') // only the exact value 'check' flips it
  } finally {
    if (saved === undefined) delete process.env.VIKE_DATA_GEN
    else process.env.VIKE_DATA_GEN = saved
  }
})

test('generateFromConfig: drizzle yields one schema file and no conflicts', () => {
  const { files, conflicts, tables } = generateFromConfig(sampleConfig(), 'drizzle')
  assert.equal(conflicts.length, 0)
  assert.equal(files.length, 1)
  assert.equal(files[0].path, 'drizzle/schema.generated.ts')
  assert.match(files[0].contents, GENERATED)
  assert.ok(tables.find((t) => t.table === 'users'))
  assert.ok(tables.find((t) => t.table === 'posts'))
})

test('generateFromConfig: the ORM selector changes the artifacts (rudder = per-fragment migrations)', () => {
  const { files } = generateFromConfig(sampleConfig(), 'rudder')
  assert.ok(files.length >= 2)
  assert.ok(files.every((f) => f.path.startsWith('database/migrations/')))
})

test('generateFromConfig: orders an FK target before its dependant (wrong input order still merges both)', () => {
  const cfg = {
    schemas: [
      defineSchema('posts', (t) => t.uuid('author_id').references('users.id')),
      defineSchema('users', (t) => t.uuid('id').primary()),
    ],
  }
  const { files, conflicts } = generateFromConfig(cfg, 'drizzle')
  assert.equal(conflicts.length, 0)
  assert.match(files[0].contents, /users/)
  assert.match(files[0].contents, /posts/)
})

test('generateFromConfig: a schema conflict yields conflicts and NO files (the gate)', () => {
  const cfg = {
    schemas: [
      defineSchema('users', (t) => t.uuid('id').primary()),
      extendSchema('users', (t) => t.string('id')), // re-defines an existing column
    ],
  }
  const { conflicts, files } = generateFromConfig(cfg, 'drizzle')
  assert.ok(conflicts.length > 0)
  assert.deepEqual(files, [])
})
