// File generation: turn the merged schema into committable, on-disk artifacts.
//
// Schema is authored once (defineSchema/extendSchema); the artifacts below are
// DERIVED. They are meant to be committed to the user's repo with a "generated,
// don't edit" header (the Prisma/Cloudflare precedent), so diffs are visible and
// CI is reproducible, while making clear the file is output, not source.
//
// Division of labour matches each ORM's model:
//   - Prisma / Drizzle are DECLARATIVE: we emit ONE schema file (desired state);
//     their own tooling (prisma migrate / drizzle-kit) derives the migrations.
//   - The native engine is the exception: WE own migrations, so we emit one
//     ordered migration file per contributed fragment (create / alter).
//
// Pure: returns [{ path, contents }] pairs. No filesystem access here — the
// binding/CLI decides where to write them.

import { toPrisma, toDrizzle, toNative } from './compilers.js'

const DONT_EDIT = [
  'GENERATED by @vike-data/universal-schema — do not edit by hand.',
  'Your schema is declared with defineSchema()/extendSchema() across your',
  'extensions; this file is derived from it. Re-run generation to update it.',
]
const header = (prefix) => DONT_EDIT.map((l) => `${prefix} ${l}`).join('\n') + '\n'

const camel = (s) => s.replace(/_([a-z])/g, (_, c) => c.toUpperCase())
const DRIZZLE_FN = { uuid: 'uuid', string: 'varchar', text: 'text', integer: 'integer', boolean: 'boolean', timestamp: 'timestamp' }
const pad = (x) => String(x).padStart(3, '0')

// ---------------------------------------------------------------- Prisma -----
// One declarative schema.prisma: a datasource/generator preamble + every model.
function prismaFile(tables) {
  const preamble =
    'datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n' +
    'generator client {\n  provider = "prisma-client-js"\n}'
  const models = tables.map(toPrisma).join('\n\n')
  return `${header('//')}\n${preamble}\n\n${models}\n`
}

// --------------------------------------------------------------- Drizzle -----
// One declarative schema.ts. toDrizzle emits a per-table import line; assembling
// a file means hoisting a SINGLE import (the union of column fns) and keeping
// only the table exports.
function drizzleFile(tables) {
  const fns = [...new Set(tables.flatMap((t) => t.columns.map((c) => DRIZZLE_FN[c.type] || 'text')))]
  const importLine = `import { pgTable, ${fns.join(', ')} } from 'drizzle-orm/pg-core'`
  const bodies = tables.map((t) => {
    const out = toDrizzle(t)
    return out.slice(out.indexOf('export const')) // drop toDrizzle's own import line
  })
  return `${header('//')}\n${importLine}\n\n${bodies.join('\n\n')}\n`
}

// ---------------------------------------------------------------- Native -----
// We own migrations here, so emit one ordered file per fragment. Creates fold in
// only their own columns; a later `extend` becomes its own alter migration, so
// the ordered ledger mirrors how the columns were actually contributed.
function nativeAlter(frag) {
  const body = frag.columns
    .map((c) => {
      let s = `t.${c.type}('${c.name}')`
      if (c.nullable) s += '.nullable()'
      if (c.unique) s += '.unique()'
      if (c.default === 'now') s += '.useCurrent()'
      else if (c.default !== undefined) s += `.default(${JSON.stringify(c.default)})`
      return `      ${s}`
    })
    .join('\n')
  return `import { Migration, Schema } from '@rudderjs/database'\n\nexport default class extends Migration {\n  async up() {\n    await Schema.table('${frag.table}', (t) => {\n${body}\n    })\n  }\n}`
}

function nativeFiles(fragments) {
  const seenCreate = new Set()
  const files = []
  for (const f of fragments) {
    if (f.mode === 'create') {
      if (seenCreate.has(f.table)) continue // dedupe a shared extension's repeated create
      seenCreate.add(f.table)
      const name = `${pad(files.length + 1)}_create_${f.table}_table`
      files.push({ path: `database/migrations/${name}.generated.ts`, contents: `${header('//')}\n${toNative(f)}\n` })
    } else {
      const cols = f.columns.map((c) => c.name).join('_')
      const name = `${pad(files.length + 1)}_alter_${f.table}_add_${cols}`
      files.push({ path: `database/migrations/${name}.generated.ts`, contents: `${header('//')}\n${nativeAlter(f)}\n` })
    }
  }
  return files
}

// Output path per ORM. Every artifact carries the "generated, don't edit" header
// AND a `.generated.` filename suffix, matching the Vike-wide convention (cf. Vike's
// own `vike.generated.d.ts`, vikejs/vike#698) that brillout asked for: the header is
// the portable signal, the suffix makes generated files obvious at a glance.
//
// Note: `prisma/schema.generated.prisma` isn't Prisma's default path, so point Prisma
// at it via package.json `"prisma": { "schema": "prisma/schema.generated.prisma" }`
// (or `--schema`). Drizzle's schema path is configured in `drizzle.config.ts` anyway.
export function generateArtifacts({ tables, fragments }, orm) {
  switch (orm) {
    case 'prisma':
      return [{ path: 'prisma/schema.generated.prisma', contents: prismaFile(tables) }]
    case 'drizzle':
      return [{ path: 'drizzle/schema.generated.ts', contents: drizzleFile(tables) }]
    case 'native':
      return nativeFiles(fragments)
    default:
      throw new Error(`generateArtifacts: unknown ORM "${orm}"`)
  }
}
