// File generation: merged schema -> committable [{ path, contents }] artifacts.
// Pure (no fs). Declarative ORMs emit ONE file; Rudder emits one per fragment.

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { defineSchema, extendSchema } from '../src/define.js'
import { mergeSchemas } from '../src/merge.js'
import { generateArtifacts } from '../src/generate.js'

const sample = () => {
  const fragments = [
    defineSchema('users', (t) => t.uuid('id').primary()),
    defineSchema('posts', (t) => t.uuid('author_id').references('users.id', { onDelete: 'cascade' })),
    extendSchema('users', (t) => t.string('nickname')),
  ]
  const { tables } = mergeSchemas(fragments)
  return { tables, fragments }
}

const GENERATED = /GENERATED by @vike-data\/universal-schema/

test('prisma generates one schema.generated.prisma with header + preamble', () => {
  const [art, ...rest] = generateArtifacts(sample(), 'prisma')
  assert.equal(rest.length, 0)
  assert.equal(art.path, 'prisma/schema.generated.prisma')
  assert.match(art.contents, GENERATED)
  assert.match(art.contents, /datasource db \{/)
  assert.match(art.contents, /model Users \{/)
  assert.match(art.contents, /model Posts \{/)
})

test('drizzle generates one schema.generated.ts with a single hoisted import', () => {
  const [art, ...rest] = generateArtifacts(sample(), 'drizzle')
  assert.equal(rest.length, 0)
  assert.equal(art.path, 'drizzle/schema.generated.ts')
  assert.match(art.contents, GENERATED)
  // exactly one import line for the whole file
  assert.equal(art.contents.match(/^import /gm).length, 1)
  assert.match(art.contents, /export const users = pgTable/)
  assert.match(art.contents, /export const posts = pgTable/)
})

test('Rudder generates one ordered migration file per fragment', () => {
  const files = generateArtifacts(sample(), 'rudder')
  assert.deepEqual(files.map((f) => f.path), [
    'database/migrations/001_create_users_table.generated.ts',
    'database/migrations/002_create_posts_table.generated.ts',
    'database/migrations/003_alter_users_add_nickname.generated.ts',
  ])
  assert.ok(files.every((f) => GENERATED.test(f.contents)))
})

test('Rudder create uses Schema.create, alter uses Schema.table', () => {
  const files = generateArtifacts(sample(), 'rudder')
  assert.match(files[0].contents, /Schema\.create\('users'/)
  assert.match(files[2].contents, /Schema\.table\('users'/)
  assert.match(files[2].contents, /t\.string\('nickname'\)/)
})

test('Rudder dedupes a repeated create of a shared extension table', () => {
  const dup = [
    defineSchema('users', (t) => t.uuid('id').primary()),
    defineSchema('users', (t) => t.uuid('id').primary()),
  ]
  const files = generateArtifacts({ tables: mergeSchemas(dup).tables, fragments: dup }, 'rudder')
  assert.equal(files.length, 1)
})

test('generateArtifacts throws on an unknown ORM', () => {
  assert.throws(() => generateArtifacts(sample(), 'mongoose'), /unknown ORM "mongoose"/)
})
