// GENERATED by vike:typed-routes via `vike generate` — do not edit by hand.
// Re-run `vike generate` to update; the source of truth is your + config.

export type Route =
  | '/'

export const routes = ['/'] as const
