// A proposed Vike-core primitive: materialize files that extensions DERIVE into
// the user's repo (committed, "generated, don't edit"), from one shared mechanism.
//
// Today every party that does this hand-rolls it:
//   - Vike itself codegens `vike.generated.d.ts` (route types, vikejs/vike#698)
//   - @vike-data codegens schema.generated.prisma / drizzle / native migrations
//   - any future extension (typed env, API clients, typed routes...) wants it too
//
// They all want the SAME thing: collect generators from the resolved config
// graph, run them, enforce one convention, write or check. That belongs in core.
//
// THE CONTRACT. A generator is a plain object:
//
//   { name: string, files(context) => Array<{ path, comment, body }> }
//
//   - `name`      identifies the generator (dedup-by-identity + header provenance)
//   - `files()`   PURE: returns logical files, NO header, NO `.generated.` policy.
//                 Returning data (not writing) keeps it testable + serializable,
//                 mirroring how @vike-data already split generate.js.
//   - `path`      where it lands in the repo; MUST contain `.generated.` (enforced)
//   - `comment`   the line-comment token for the target language (`//`, `#`, `--`)
//   - `body`      the file contents WITHOUT the header (core stamps it)
//
// Core owns the cross-cutting parts every generator would otherwise duplicate:
// the header text, the `.generated.` suffix rule, collision policy, and a
// `--check` drift mode for CI. One trigger (`vike generate`), one convention.

import { mkdir, writeFile, readFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

const SUFFIX = '.generated.'

function stampHeader({ name, comment, body }) {
  const lines = [
    `GENERATED by ${name} via \`vike generate\` — do not edit by hand.`,
    `Re-run \`vike generate\` to update; the source of truth is your + config.`,
  ]
  return lines.map((l) => `${comment} ${l}`).join('\n') + '\n\n' + body
}

// Collect every generator's logical files, validate the convention, stamp the
// header, and reject collisions (two generators claiming the same path). Pure:
// returns the resolved file set, no filesystem access — write()/check() do that.
export function collect(generators, context) {
  const byPath = new Map()
  for (const gen of generators) {
    if (!gen || typeof gen.files !== 'function') {
      throw new Error(`codegen: generator "${gen?.name ?? '?'}" has no files() function`)
    }
    for (const f of gen.files(context)) {
      if (!f.path.includes(SUFFIX)) {
        throw new Error(`codegen: "${gen.name}" path "${f.path}" must contain "${SUFFIX}"`)
      }
      const prior = byPath.get(f.path)
      if (prior && prior.name !== gen.name) {
        throw new Error(`codegen: path collision on "${f.path}" between "${prior.name}" and "${gen.name}"`)
      }
      byPath.set(f.path, { path: f.path, name: gen.name, contents: stampHeader({ name: gen.name, comment: f.comment, body: f.body }) })
    }
  }
  return [...byPath.values()]
}

// Materialize: write mode persists files; check mode diffs against disk and
// reports drift (exit-nonzero in CI keeps committed generated files honest).
export async function materialize({ generators, context, mode = 'write', cwd = process.cwd() }) {
  const files = collect(generators, context)
  const report = { mode, written: [], drift: [], ok: [] }

  for (const f of files) {
    const abs = join(cwd, f.path)
    if (mode === 'check') {
      let current = null
      try {
        current = await readFile(abs, 'utf8')
      } catch {
        current = null
      }
      if (current === f.contents) report.ok.push(f.path)
      else report.drift.push({ path: f.path, reason: current === null ? 'missing' : 'stale' })
    } else {
      await mkdir(dirname(abs), { recursive: true })
      await writeFile(abs, f.contents)
      report.written.push(f.path)
    }
  }
  return report
}
