// GENERATED by @vike-data/vike-schema via `vike generate` — do not edit by hand.
// Re-run `vike generate` to update; the source of truth is your + config.

import { Migration, Schema } from '@rudderjs/database'

export default class extends Migration {
  async up() {
    await Schema.create('_migrations', (t) => {
      t.integer('id').primary()
      t.string('name').unique()
      t.integer('batch')
    })
  }
}
