// GENERATED by @vike-data/vike-schema via `vike generate` — do not edit by hand.
// Re-run `vike generate` to update; the source of truth is your + config.

import { Migration, Schema } from '@rudderjs/database'

export default class extends Migration {
  async up() {
    await Schema.create('subscriptions', (t) => {
      t.uuid('id').primary()
      t.uuid('user_id')
      t.string('plan')
      t.integer('seats').default(1)
      t.boolean('active').default(true)
      t.timestamp('created_at').useCurrent()
      t.timestamp('updated_at').useCurrent()
    })
  }
}
