// GENERATED by @vike-data/vike-schema via `vike generate` — do not edit by hand.
// Re-run `vike generate` to update; the source of truth is your + config.

import { Migration, Schema } from '@rudderjs/database'

export default class extends Migration {
  async up() {
    await Schema.table('users', (t) => {
      t.string('stripe_customer_id').nullable()
    })
  }
}
