// GENERATED by @vike-data/universal-schema — do not edit by hand.
// Your schema is declared with defineSchema()/extendSchema() across your
// extensions; this file is derived from it. Re-run generation to update it.

import { Migration, Schema } from '@rudderjs/database'

export default class extends Migration {
  async up() {
    await Schema.create('organizations', (t) => {
      t.uuid('id').primary()
      t.string('name')
      t.string('slug').unique()
      t.uuid('owner_id').references('id').on('users').onDelete('restrict')
      t.timestamp('created_at').useCurrent()
      t.timestamp('updated_at').useCurrent()
    })
  }
}
