// GENERATED by @vike-data/universal-schema — do not edit by hand.
// Your schema is declared with defineSchema()/extendSchema() across your
// extensions; this file is derived from it. Re-run generation to update it.

import { Migration, Schema } from '@rudderjs/database'

export default class extends Migration {
  async up() {
    await Schema.create('memberships', (t) => {
      t.uuid('id').primary()
      t.uuid('organization_id')
      t.uuid('user_id')
      t.string('role').default("member")
      t.timestamp('created_at').useCurrent()
      t.timestamp('updated_at').useCurrent()
    })
  }
}
