// GENERATED by @vike-data/universal-schema — do not edit by hand.
// Your schema is declared with defineSchema()/extendSchema() across your
// extensions; this file is derived from it. Re-run generation to update it.

import { Migration, Schema } from '@rudderjs/database'

export default class extends Migration {
  async up() {
    await Schema.create('event__subscription_events', (t) => {
      t.uuid('id').primary()
      t.uuid('organization_id').references('id').on('organizations').onDelete('cascade')
      t.string('type')
      t.string('plan')
      t.integer('seats').default(1)
      t.string('stripe_event_id').unique()
      t.timestamp('occurred_at')
      t.timestamp('created_at').useCurrent()
    })
  }
}
